In [12]:
import numpy as np
# Tạo mảng
a = np.array([4,2,3])
print(a)
# In ra phần tử
element = a[1]
print(element)

[4 2 3]
2


In [14]:
# Tạo mảng 2 chiều
matrix = np.array([[5,4,2],[1,2,3],[7,4,9]])
print("Matrix:")
print(matrix)
# In 1 phần tử
element = matrix[1,2]
print(element)

Matrix:
[[5 4 2]
 [1 2 3]
 [7 4 9]]
3


In [10]:
# Cách tạo mảng
# Tạo mảng số 0
a = np.zeros(5)
print(a)

# Tạo mảng só 1
a = np.ones(5)

a = np.empty(5)
print(a)

# Tạo mảng từ 0 đến 100
a = np.arange(100)
print(a)

# Tạo mảng gồm các phần tử với khoảng cách đều nhau
a = np.linspace(0, 10, num=5)
print(a)


# Xác định kiểu dữ liệu
a = np.ones(5, dtype=np.int64)
a

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.   2.5  5.   7.5 10. ]


array([1, 1, 1, 1, 1], dtype=int64)

In [2]:
# Tạo mảng ban đầu

arr = np.array([3,1,4,5,2])
print(arr)


In [11]:
# Thêm xóa sắp xếp mảng
# Tạo mảng
arr = np.array([5,6,4,3,2,1])
# Sắp xếp
arr = np.sort(arr)
print(arr)
# Sắp xếp ngược
arr =  np.sort(arr)[::-1]
print(arr)
# Thêm phần tử vào mảng
arr = np.append(arr, 100)
print(arr)
# Xóa đi một ví trí nào đó trong mảng
arr = np.delete(arr, 3)
print(arr)

[1 2 3 4 5 6]
[6 5 4 3 2 1]
[  6   5   4   3   2   1 100]
[  6   5   4   2   1 100]


In [20]:
# Tạo mảng 2 chiều
arr = np.array([[3,1,2],[24,15,6],[23,8,9]])
sap_xep_theo_hang = np.sort(arr, axis = 1)# tăng dần
print(sap_xep_theo_hang)
sap_xep_theo_cot = np.sort(arr, axis = 0)# tăng dần
print(sap_xep_theo_cot)


[[ 1  2  3]
 [ 6 15 24]
 [ 8  9 23]]
[[ 3  1  2]
 [23  8  6]
 [24 15  9]]


In [22]:
# Tạo một mảng 2 chiều
arr = np.array([[3, 31, 12],
                [24, 26, 8],
                [19,17, 8]])

sap_xep_theo_hang = -np.sort(-arr, axis=1) # giảm dần
print(sap_xep_theo_hang)

sap_xep_theo_cot = -np.sort(-arr, axis=0) # giảm dần
print(sap_xep_theo_cot)

[[31 12  3]
 [26 24  8]
 [19 17  8]]
[[24 31 12]
 [19 26  8]
 [ 3 17  8]]


In [24]:
# Tạo một mảng 2D
arr = np.array([[11, 12, 33], [7, 78, 9]])

# Sử dụng các thuộc tính để lấy thông tin về mảng
so_chieu = arr.ndim  # Số chiều (2 chiều)
kich_thuoc = arr.size  # Kích thước (tổng số phần tử, 6)
hinh_dang = arr.shape  # Hình dạng (số hàng x số cột, (2, 3))

print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [25]:
# Chuyển đổi kiểu dữ liệu
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [26]:
# Thay đổi hình dạng của mảng
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [28]:
reshaped_arr = reshaped_arr.flatten() # Chuyển thành mảng 1 chiều
print(reshaped_arr)

[1 2 3 4 5 6]


In [27]:
# xóa vị trí nào đó trong mảng
arr = np.delete(arr,3)
print(arr)

[1 2 3 5 6]


In [ ]:
# Cắt lát mảng
arr = np.array([1, 2, 3, 4, 5])

sub_arr = arr[1:4]  # Cắt từ phần tử thứ 1 đến 4
print(sub_arr) # 2 3 4 5

sub_arr = arr[:-1]  # 1 2 3 4
print(sub_arr)

sub_arr = arr[-2:]  # 4 5 
print(sub_arr)

In [30]:
# Chuyển vị mảng
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# Để chuyển vị mảng, chúng ta có thể sử dụng .T hoặc hàm numpy.transpose().
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Nối mảng
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)